version: '3.4'

services:
  voicechanger:
    image: voicechanger:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    entrypoint:
      - /bin/bash
      - -c
    command: 
      - >
        python
        MMVCServerSIO.py
        --host 0.0.0.0
        -p 6006
        --content_vec_500 pretrain/checkpoint_best_legacy_500.pt
        --content_vec_500_onnx pretrain/content_vec_500.onnx
        --content_vec_500_onnx_on true
        --hubert_base pretrain/hubert_base.pt
        --hubert_base_jp pretrain/rinna_hubert_base_jp.pt
        --hubert_soft pretrain/hubert/hubert-soft-0d54a1f4.pt
        --nsf_hifigan pretrain/nsf_hifigan/model
        --crepe_onnx_full pretrain/crepe_onnx_full.onnx
        --crepe_onnx_tiny pretrain/crepe_onnx_tiny.onnx
        --rmvpe pretrain/rmvpe.pt
        --model_dir model_dir
        --samples samples.json
    ports:
      - 6006:6006
    volumes:
      - ./docker_folder/model_dir:/app/server/model_dir
      - ./docker_folder/pretrain:/app/server/pretrain
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]